DROP TABLE HOSPITALS_TRANSFORMED; 
CREATE TABLE HOSPITALS_TRANSFORMED AS SELECT * FROM HOSPITALS;

DROP TABLE EFFECTIVE_CARE_TRANSFORMED; 
CREATE TABLE EFFECTIVE_CARE_TRANSFORMED AS SELECT Provider_ID, Measure_ID, Score, Sample, Foot_Note from EFFECTIVE_CARE WHERE Score !='Not Available';
DROP TABLE MEASURES_TRANSFORMED;
CREATE TABLE MEASURES_TRANSFORMED as SELECT * from MEASURES;
DROP TABLE READMISSIONS_TRANSFORMED;
CREATE TABLE READMISSIONS_TRANSFORMED AS SELECT Provider_ID, Measure_ID, Compared_To_National, Denominator,  Score, Lower_Estimate, Higher_Estimate, Foot_Note FROM READMISSIONS  WHERE Score !='Not Available';
DROP TABLE SURVEYS_RESPONSES_TRANSFORMED;
CREATE TABLE SURVEYS_RESPONSES_TRANSFORMED AS SELECT Provider_ID,substring(Nurse_Achievment,0,1) ,substring( Nurse_Improvement,0,1) , substring(Nurse_Dimension,0,1) ,substring(Doctor_Achievement,0,1) , substring(Doctor_Improvement,0,1) ,substring(Doctor_Dimension,0,1) , substring(Staff_Achievement,0,1) , substring(Staff_Improvement,0,1) , substring(Staff_Dimension,0,1) , substring(Management_Achivement,0,1) ,substring(Management_Improvement,0,1) , substring(Management_Dimension,0,1) , substring(Med_Achivement,0,1) , substring(Med_Improvement,0,1) ,substring(Med_Dimension,0,1) ,substring(Env_Achievement,0,1) ,substring(Env_Improvement,0,1) ,substring(Env_Dimension,0,1) ,substring(Discharge_Achivement,0,1) ,substring(Discharge_Improvement,0,1) ,substring(Discharge_Dimension,0,1) ,substring(Overall_Achivement,0,1) , substring(Overall_Improvement,0,1) , substring(Overall_Dimension,0,1) FROM SURVEYS_RESPONSES where Nurse_Achievment !='Not Available' and Nurse_Improvement !='Not Available' and Nurse_Dimension !='Not Available' and Doctor_Achievement !='Not Available' and Doctor_Improvement !='Not Available' and Doctor_Dimension !='Not Available' and Staff_Achievement !='Not Available' and Staff_Improvement !='Not Available' and Staff_Dimension !='Not Available' and Management_Achivement !='Not Available' and Management_Improvement !='Not Available' and Management_Dimension !='Not Available' and Med_Achivement !='Not Available' and Med_Improvement !='Not Available' and Med_Dimension !='Not Available' and Env_Achievement !='Not Available' and Env_Improvement !='Not Available' and Env_Dimension !='Not Available' and Discharge_Achivement !='Not Available' and Discharge_Improvement !='Not Available' and Discharge_Dimension !='Not Available' and Overall_Achivement !='Not Available' and Overall_Improvement !='Not Available' and Overall_Dimension !='Not Available';
