DROP TABLE HOSPITALS_TRANSFORMED; 
CREATE TABLE HOSPITALS_TRANSFORMED AS SELECT * FROM HOSPITALS;

DROP TABLE EFFECTIVE_CARE_TRANSFORMED; 
CREATE TABLE EFFECTIVE_CARE_TRANSFORMED AS SELECT Provider_ID, Measure_ID, Score, Sample, Foot_Note from EFFECTIVE_CARE WHERE Score !='Not Available';
DROP TABLE MEASURES_TRANSFORMED;
CREATE TABLE MEASURES_TRANSFORMED as SELECT * from MEASURES;
DROP TABLE READMISSIONS_TRANSFORMED;
CREATE TABLE READMISSIONS_TRANSFORMED AS SELECT Provider_ID, Measure_ID, Compared_To_National, Denominator,  Score, Lower_Estimate, Higher_Estimate, Foot_Note FROM READMISSIONS  WHERE Score !='Not Available';
DROP TABLE SURVEYS_RESPONSES_TRANSFORMED;
CREATE TABLE SURVEYS_RESPONSES_TRANSFORMED AS SELECT Provider_ID,substring(Nurse_Achievment,0,1) Nurse_Achievment,substring( Nurse_Improvement,0,1) Nurse_Improvement, substring(Nurse_Dimension,0,1) Nurse_Dimension ,substring(Doctor_Achievement,0,1) Doctor_Achievement, substring(Doctor_Improvement,0,1) Doctor_Improvement ,substring(Doctor_Dimension,0,1) Doctor_Dimension, substring(Staff_Achievement,0,1) Staff_Achievement, substring(Staff_Improvement,0,1) Staff_Improvement, substring(Staff_Dimension,0,1) Staff_Dimension, substring(Management_Achivement,0,1) Management_Achievement,substring(Management_Improvement,0,1) Management_Improvement, substring(Management_Dimension,0,1) Management_Dimension, substring(Med_Achivement,0,1) Med_Achievement, substring(Med_Improvement,0,1) Med_Improvement,substring(Med_Dimension,0,1) Med_Dimension,substring(Env_Achievement,0,1) Env_Achievement,substring(Env_Improvement,0,1) Env_Improvement,substring(Env_Dimension,0,1) Env_Dimension,substring(Discharge_Achivement,0,1) Discharge_Achivement, substring(Discharge_Improvement,0,1) Discharge_Improvement, substring(Discharge_Dimension,0,1) Discharge_Dimension, substring(Overall_Achivement,0,1) Overall_Achievement, substring(Overall_Improvement,0,1) Overall_Improvement, substring(Overall_Dimension,0,1) Overall_Dimension, HCAHPS_Base_Score, HCAHPS_Consistency_Score  FROM SURVEYS_RESPONSES where Nurse_Achievment !='Not Available' and Nurse_Improvement !='Not Available' and Nurse_Dimension !='Not Available' and Doctor_Achievement !='Not Available' and Doctor_Improvement !='Not Available' and Doctor_Dimension !='Not Available' and Staff_Achievement !='Not Available' and Staff_Improvement !='Not Available' and Staff_Dimension !='Not Available' and Management_Achivement !='Not Available' and Management_Improvement !='Not Available' and Management_Dimension !='Not Available' and Med_Achivement !='Not Available' and Med_Improvement !='Not Available' and Med_Dimension !='Not Available' and Env_Achievement !='Not Available' and Env_Improvement !='Not Available' and Env_Dimension !='Not Available' and Discharge_Achivement !='Not Available' and Discharge_Improvement !='Not Available' and Discharge_Dimension !='Not Available' and Overall_Achivement !='Not Available' and Overall_Improvement !='Not Available' and Overall_Dimension !='Not Available';
